version: '3.8'

services:
  smart_search_db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - smart_search_volume_data:/var/lib/postgresql/data

volumes:
  smart_search_volume_data:
